### ISSUE TITLE
[Feature request] Ignore speaking users name if only one user has TTS activated.

### ISSUE THREAD

**Issue by Zelaf** [Erallie/voicely-text#3]
**Is your feature request related to a problem? Please describe.**
Currently if only one user has TTS enabled their name is spoken before the message is being said.

**Describe the solution you'd like**
If only one user has it enabled it would expedite the conversing with people who are not using the TTS to skip saying the users name if it's only one user who has TTS enabled. If more than one user has it enabled it should however say their name before hand.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Erallie** [comment]
@Zelaf Currently, how the bot is set up, the bot only speaks the user's name if it's the first time they've spoken in the past 30 seconds, or if they were not the last person who spoke. It doesn't read the user's name otherwise. Because of this, I don't think this is an issue. But if you still have a problem with this, please comment again, and I will reopen the issue!
